
import { Card, CardContent, CardHeader, CardTitle } from "@/react-app/components/ui/card";

const PrivacyPage = () => {
  return (
    <div className="container mx-auto py-8 px-4 max-w-4xl">
      <div className="text-center mb-8">
        <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
        <p className="text-muted-foreground">
          Your privacy is important to us
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>ZoneRight Privacy Policy</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div>
            <h3 className="text-lg font-semibold mb-2">Data Collection</h3>
            <p className="text-muted-foreground">
              ZoneRight does not collect, store, or transmit any personal data. All heart rate data, session information, 
              and app preferences are stored locally on your device and never leave your device.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold mb-2">Local Storage Only</h3>
            <p className="text-muted-foreground">
              All data generated by the app, including your heart rate readings, workout sessions, and settings, 
              are stored exclusively on your iOS device using SwiftData. This ensures complete privacy and offline functionality.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold mb-2">No External Communication</h3>
            <p className="text-muted-foreground">
              ZoneRight operates completely offline and does not communicate with external servers, analytics services, 
              or third-party data collection platforms. Your fitness data remains private to you.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold mb-2">Bluetooth Connectivity</h3>
            <p className="text-muted-foreground">
              The app only uses Bluetooth to connect to your heart rate monitoring devices (such as Whoop bands or chest straps). 
              This connection is used solely to receive heart rate data for real-time monitoring during your workouts.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold mb-2">Updates to This Policy</h3>
            <p className="text-muted-foreground">
              Any changes to this privacy policy will be reflected in app updates. Since we don't collect any data, 
              any policy changes would only serve to further clarify our commitment to your privacy.
            </p>
          </div>

          <div className="bg-muted p-4 rounded-lg">
            <p className="text-sm font-medium">
              Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default PrivacyPage;